### ISSUE TITLE
yearsExperienceFromBeginningOf() test doesn't have correct value

### ISSUE THREAD

**Issue by cdhenry** [learn-co-curriculum/js-object-oriented-classes-travel-lab#12]
If you subtract 2017 from 1995 the difference is 22 years, but the test is expect 21.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @cdhenry.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by morgvanny** [comment]
I'm reopening this issue, because 21 is correct. August of 1995 to January of 2017 is not 22 years, even if you round.

Edit:
It appears that to solve this issue, we swapped the date to January of 1995 instead, so it actually is 22 years now. I'll re-close the issue, although I feel like we're just making the test less robust, allowing people to subtract years without having to take actual dates into account.
